[FROM-UPSTREAM] platform/x86: lenovo: gamezone needs "other mode"
Registering the "other mode" notifier fails if that is disabled:

x86_64-linux-ld: drivers/platform/x86/lenovo/wmi-gamezone.o: in function `lwmi_gz_probe':
wmi-gamezone.c:(.text+0x336): undefined reference to `devm_lwmi_om_register_notifier'

This could be fixed by adding a stub helper, but a Kconfig 'select'
seems simpler here.

Fixes: 22024ac5366f ("platform/x86: Add Lenovo Gamezone WMI Driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
(cherry picked from commit cf8761853263abb96035cd48b8b74eab7a3b037a)
Signed-off-by: Derek J. Clark <derekjohn.clark@gmail.com>