fixup! [FOR-UPSTREAM] drm/amdgpu: Use drm_exec to reliably pin fb buffers
The original commit changed the function signature for amdgpu_bo_pin but
only updated its call site on dce_v10, but not on dce_v8 or dce_v6,
probably because we don't build those in the SteamOS config, which
resulted in the build failure when building with an upstream defconfig:

In file included from drivers/gpu/drm/amd/amdgpu/amdgpu_ring.h:27,
                 from drivers/gpu/drm/amd/amdgpu/amdgpu_ctx.h:29,
                 from drivers/gpu/drm/amd/amdgpu/amdgpu.h:43,
                 from drivers/gpu/drm/amd/amdgpu/dce_v6_0.c:32:
drivers/gpu/drm/amd/amdgpu/dce_v6_0.c: In function ‘dce_v6_0_crtc_do_set_base’:
./include/uapi/drm/amdgpu_drm.h:113:41: error: passing argument 2 of ‘amdgpu_bo_pin’ makes pointer from integer without a cast [-Wint-conversion]

Copy the changes done in dce_v10 to dce_v6 and dce_v8, since they're
identical, to fix the build failure.

Signed-off-by: Nícolas F. R. A. Prado <nfraprado@collabora.com>